name: fquick_cli
description: F-Quick CLI to use as a Flutter Starter kit.
version: 0.0.1-dev.9
# publish_to: none
homepage: https://github.com/durgeshgit20/as_flutter_cli
repository: https://github.com/durgeshgit20/as_flutter_cli

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason: ^0.1.1
  mason_logger: ^0.3.3
  path: ^1.9.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.8.0
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^9.0.0

executables:
  fquick:

topics:
  - starter
  - uikit
  - cli
  - widgets
