name: archipelago_cli
description: Archipelago CLI to use Archipelago Flutter Starter kit.
version: 0.0.1-dev.9
# publish_to: none
homepage: https://github.com/banua-coder/archipelago-cli
repository: https://github.com/banua-coder/archipelago-cli

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  mason: ^0.1.0
  mason_logger: ^0.3.2
  path: ^1.9.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0

executables:
  archipelago:

topics:
  - starter
  - uikit
  - cli
  - widgets
